#!/bin/bash
NAME=$1
NOW=$(date "+%Y.%m.%d %T")


if [ -z "$NAME" ]
then
        echo "Error: set problem name"
        return 1
fi

mkdir $NAME && cd $NAME

touch in.txt

source mkf a

source mk_make a

echo "Gerated Problem $NAME at $NOW"

gvim -p a.cc "in.txt" Makefile
